query articleQuery($displayName: String!, $title: String!, $readerUid: String = ""){
  article(displayName: $displayName, title: $title){
    uid,
    title,
    currentVersion{content, uid},
    dateOfLastUpdate,
    user{displayName},
    totalLikes,
    isLikedByReader(readerUid: $readerUid),
    tags
  }
}
