query articlesOfUserQuery($displayName: String!){
  articlesOfUser(displayName: $displayName){
    title,
    dateOfLastUpdate,
    totalLikes,
    currentVersion{state},
    tags,
    user{displayName}
  }
}
