query articleQuery($displayName: String!, $title: String!){
  article(displayName: $displayName, title: $title){
    title,
    currentVersion{content},
    dateOfLastUpdate,
    user{displayName},
    totalLikes
  }
}
