query profileQuery($displayName: String!){
  profile(displayName: $displayName){
    displayName,
    email,
    tags,
    articles{
      title,
      totalLikes,
      dateOfCreation,
      dateOfLastUpdate,
      currentVersion{
        state
      }
    },
    likedArticles{
      article{
        title,
        user{
          displayName
        }
        currentVersion{
          content
        }
      }
    }
  }
}
